version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casar-test
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
    #COMMAND: [ "pm2-runtime", "start", "npm", "--", "start" ]
