name: Testes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Jest:
    name: Testes unitátios do app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Instalando dependências
        run: |
          npm install

      - name: Run Jest testes
        run: npm run test

  Cypress:
    name: Testes de integração do app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build da aplicação Next
        env:
          GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
          NEXT_PUBLIC_GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
        run: npm run build

      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v3
        with:
          start: npm run start
          wait-on: "http://localhost:3000"
