name: Testes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    name: Instalar dependências e build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Build da aplicação Next
        env:
          GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
          NEXT_PUBLIC_GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
        run: npm run build

      - name: Salvar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            node_modules
            .next
            package.json

  jest:
    name: Testes Unitários (Jest)
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Rodar testes Jest
        run: npm run test

  cypress:
    name: Testes de Integração (Cypress)
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          wait-on: "http://localhost:3000"
